<x-app-layout>
    <x-slot:header>Artikel Pusat Pengetahuan</x-slot:header>
    <div class="mx-auto max-w-5xl"><a class="mb-6 inline-flex items-center gap-2 text-sm font-semibold text-muted hover:text-accent" href="{{ route('knowledge.index') }}"><x-icon name="arrow" size="16" class="rotate-180" /> Semua artikel</a>
        <article class="panel"><div class="p-6 sm:p-9 lg:p-12"><div class="flex flex-wrap items-center justify-between gap-3"><span class="eyebrow">{{ $article->category->name }}</span><x-badge :value="$article->status" /></div><h1 class="mt-6 max-w-4xl text-3xl font-bold leading-tight tracking-[-0.04em] sm:text-5xl">{{ $article->title }}</h1><p class="mt-4 text-sm text-muted">Oleh {{ $article->author->name }} &middot; {{ $article->published_at?->format('d M Y') ?? 'Belum diterbitkan' }} &middot; {{ $article->view_count }} dilihat</p><p class="mt-8 rounded-lg border border-[#CDE5DE] bg-accent-pale p-5 text-base leading-7 text-[#365E54]">{{ $article->summary }}</p>
            <section class="mt-10 border-t border-line pt-8"><p class="eyebrow">01</p><h2 class="mt-3 text-2xl font-bold tracking-[-0.03em]">Kemungkinan penyebab</h2><div class="mt-4 whitespace-pre-line text-sm leading-7 text-[#444440] sm:text-base">{{ $article->cause }}</div></section>
            <section class="mt-10 border-t border-line pt-8"><p class="eyebrow">02</p><h2 class="mt-3 text-2xl font-bold tracking-[-0.03em]">Langkah penyelesaian</h2><div class="mt-4 whitespace-pre-line text-sm leading-7 text-[#444440] sm:text-base">{{ $article->solution_steps }}</div></section>
            @if($article->additional_notes)<section class="mt-10 rounded-lg border border-amber-200 bg-amber-50 p-5"><h2 class="font-bold">Catatan tambahan</h2><div class="mt-2 whitespace-pre-line text-sm leading-6 text-amber-900">{{ $article->additional_notes }}</div></section>@endif
            <div class="mt-10 flex flex-wrap gap-3 border-t border-line pt-6">@can('update', $article)<a class="btn-secondary" href="{{ route('knowledge.edit', $article) }}">Edit artikel</a>@endcan @can('delete', $article)<form method="POST" action="{{ route('knowledge.destroy', $article) }}" onsubmit="return confirm('Hapus artikel ini?')">@csrf @method('DELETE')<button class="btn-danger" type="submit">Hapus</button></form>@endcan</div></div></article>
        @if($related->isNotEmpty())<h2 class="mb-4 mt-8 section-title">Artikel terkait</h2><div class="grid gap-4 sm:grid-cols-2">@foreach($related as $item)<a class="card group flex items-center justify-between gap-3 font-semibold hover:border-accent hover:text-accent" href="{{ route('knowledge.show', $item) }}"><span>{{ $item->title }}</span><x-icon name="arrow" size="16" class="text-muted" /></a>@endforeach</div>@endif
    </div>
</x-app-layout>
