<x-app-layout>
    <x-slot:header>Laporan</x-slot:header>
    <x-page-header eyebrow="Insight operasional" title="Laporan operasional" description="Tinjau data helpdesk dan aset berdasarkan periode serta filter yang dipilih.">
        <x-slot:actions><a class="btn-secondary" href="{{ route('reports.excel', ['type' => $type] + request()->query()) }}"><x-icon name="download" size="17" /> Excel</a><a class="btn-secondary" href="{{ route('reports.pdf', ['type' => $type] + request()->query()) }}"><x-icon name="download" size="17" /> PDF</a><button type="button" class="btn-secondary" onclick="window.print()">Cetak</button></x-slot:actions>
    </x-page-header>
    <div class="mb-6 flex gap-2 overflow-x-auto pb-1" role="navigation" aria-label="Jenis laporan">@foreach(['tickets' => 'Tiket', 'assets' => 'Inventaris', 'repairs' => 'Perbaikan', 'technicians' => 'Teknisi'] as $key => $label)<a class="{{ $type === $key ? 'btn-primary' : 'btn-secondary' }} shrink-0" href="{{ route('reports.index', $key) }}">{{ $label }}</a>@endforeach</div>
    <form class="panel mb-6" method="GET" aria-label="Filter laporan"><div class="panel-body"><div class="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><div><label class="label" for="report_from">Dari tanggal</label><input id="report_from" class="input" type="date" name="date_from" value="{{ request('date_from') }}"></div><div><label class="label" for="report_to">Sampai tanggal</label><input id="report_to" class="input" type="date" name="date_to" value="{{ request('date_to') }}"></div>
        @if($type === 'tickets')
            <div><label class="label" for="report_status">Status</label><select id="report_status" class="input" name="status"><option value="">Semua</option>@foreach(['baru', 'ditugaskan', 'diproses', 'menunggu_konfirmasi', 'selesai', 'dibatalkan'] as $value)<option value="{{ $value }}" @selected(request('status') === $value)>{{ str($value)->replace('_', ' ')->title() }}</option>@endforeach</select></div>
            <div><label class="label" for="report_priority">Prioritas</label><select id="report_priority" class="input" name="priority"><option value="">Semua</option>@foreach(['rendah', 'sedang', 'tinggi', 'kritis'] as $value)<option value="{{ $value }}" @selected(request('priority') === $value)>{{ ucfirst($value) }}</option>@endforeach</select></div>
            <div><label class="label" for="report_category">Kategori</label><select id="report_category" class="input" name="category"><option value="">Semua</option>@foreach($lookups['ticketCategories'] as $item)<option value="{{ $item->id }}" @selected(request('category') == $item->id)>{{ $item->name }}</option>@endforeach</select></div>
            <div><label class="label" for="report_technician">Teknisi</label><select id="report_technician" class="input" name="technician"><option value="">Semua</option>@foreach($lookups['technicians'] as $item)<option value="{{ $item->id }}" @selected(request('technician') == $item->id)>{{ $item->name }}</option>@endforeach</select></div>
            <div><label class="label" for="report_department">Departemen</label><select id="report_department" class="input" name="department"><option value="">Semua</option>@foreach($lookups['departments'] as $item)<option value="{{ $item->id }}" @selected(request('department') == $item->id)>{{ $item->name }}</option>@endforeach</select></div>
        @elseif($type === 'assets')
            <div><label class="label" for="report_status">Status</label><input id="report_status" class="input" name="status" value="{{ request('status') }}"></div><div><label class="label" for="report_condition">Kondisi</label><input id="report_condition" class="input" name="condition" value="{{ request('condition') }}"></div><div><label class="label" for="report_category">Kategori</label><select id="report_category" class="input" name="category"><option value="">Semua</option>@foreach($lookups['assetCategories'] as $item)<option value="{{ $item->id }}" @selected(request('category') == $item->id)>{{ $item->name }}</option>@endforeach</select></div>
        @elseif($type === 'repairs')
            <div><label class="label" for="report_technician">Teknisi</label><select id="report_technician" class="input" name="technician"><option value="">Semua</option>@foreach($lookups['technicians'] as $item)<option value="{{ $item->id }}" @selected(request('technician') == $item->id)>{{ $item->name }}</option>@endforeach</select></div>
        @endif
    </div><div class="mt-5 flex justify-end gap-2"><a class="btn-secondary" href="{{ route('reports.index', $type) }}">Reset</a><button class="btn-primary" type="submit">Terapkan filter</button></div></div></form>
    <div class="table-wrap"><table class="table"><thead><tr>@foreach($headers as $header)<th>{{ $header }}</th>@endforeach</tr></thead><tbody>@forelse($rows as $row)<tr>@foreach($row as $cell)<td class="!whitespace-normal">{{ is_numeric($cell) && str_contains(strtolower($headers[$loop->index] ?? ''), 'biaya') ? 'Rp '.number_format($cell, 0, ',', '.') : $cell }}</td>@endforeach</tr>@empty<tr><td colspan="{{ count($headers) }}" class="!p-0"><x-empty-state title="Tidak ada data" description="Tidak ada data yang sesuai dengan filter laporan ini." icon="report" /></td></tr>@endforelse</tbody></table></div><p class="mt-3 text-sm text-muted">{{ count($rows) }} baris data &middot; Filter aktif diterapkan pada ekspor Excel dan PDF.</p>
</x-app-layout>
