<x-app-layout>
    <x-slot:header>Detail Aset {{ $asset->asset_code }}</x-slot:header>
    <a class="mb-6 inline-flex items-center gap-2 text-sm font-semibold text-muted hover:text-accent" href="{{ route('assets.index') }}"><x-icon name="arrow" size="16" class="rotate-180" /> Inventaris</a>
    <x-page-header :eyebrow="$asset->asset_code" :title="$asset->name" description="Informasi perangkat, penugasan, perbaikan, dan tiket terkait.">
        <x-slot:actions>
            @can('update', $asset)<a class="btn-secondary" href="{{ route('assets.edit', $asset) }}">Edit aset</a>@if(!$asset->assigned_user_id)<a class="btn-primary" href="{{ route('assets.assign.create', $asset) }}">Tugaskan</a>@endif @endcan
            @if(auth()->user()->role !== 'user')<a class="btn-secondary" href="{{ route('repairs.create', $asset) }}"><x-icon name="plus" size="17" /> Perbaikan</a>@endif
        </x-slot:actions>
    </x-page-header>
    <div class="mb-6 flex flex-wrap gap-2"><x-badge :value="$asset->condition" /><x-badge :value="$asset->status" /></div>
    <div class="grid gap-6 lg:grid-cols-3">
        <x-panel title="Informasi perangkat" class="lg:col-span-2"><dl class="grid gap-x-6 gap-y-5 text-sm sm:grid-cols-2">@foreach([['Kode aset', $asset->asset_code], ['Kategori', $asset->category->name], ['Merek / model', $asset->brand.' / '.$asset->model], ['Nomor serial', $asset->serial_number ?? '-'], ['Lokasi', $asset->location], ['Pengguna', $asset->assignedUser?->name ?? 'Tidak ditugaskan'], ['Tanggal beli', $asset->purchase_date?->format('d M Y') ?? '-'], ['Garansi', $asset->warranty_end_date?->format('d M Y') ?? '-']] as [$label, $value])<div><dt class="text-xs font-semibold uppercase tracking-wider text-muted">{{ $label }}</dt><dd class="mt-1.5 font-semibold text-ink">{{ $value }}</dd></div>@endforeach</dl>@if($asset->specifications)<div class="mt-6 border-t border-line pt-5"><h3 class="text-sm font-bold">Spesifikasi</h3><p class="mt-2 whitespace-pre-line rounded-lg bg-[#FAFAF8] p-4 text-sm leading-6 text-muted">{{ $asset->specifications }}</p></div>@endif</x-panel>
        <x-panel title="Biaya perbaikan"><p class="text-3xl font-bold tracking-[-0.04em]">Rp {{ number_format($asset->repairs->sum('repair_cost'), 0, ',', '.') }}</p><p class="mt-2 text-sm text-muted">{{ $asset->repairs->count() }} catatan perbaikan</p>
            @can('update', $asset) @if($asset->assigned_user_id)<form class="mt-6 space-y-4 border-t border-line pt-5" method="POST" action="{{ route('assets.return', $asset) }}">@csrf @method('PUT')<div><label class="label" for="return_condition">Kondisi saat kembali</label><select id="return_condition" class="input" name="condition">@foreach(['baik', 'perlu_perawatan', 'rusak_ringan', 'rusak_berat'] as $value)<option value="{{ $value }}">{{ str($value)->replace('_', ' ')->title() }}</option>@endforeach</select></div><div><label class="label" for="return_notes">Catatan pengembalian</label><textarea id="return_notes" class="input" name="notes" rows="3"></textarea></div><button class="btn-primary w-full" type="submit">Catat pengembalian</button></form>@endif @endcan
        </x-panel>
    </div>
    <div class="mt-6 grid gap-6 lg:grid-cols-2">
        <x-panel title="Riwayat penugasan"><div class="space-y-3">@forelse($asset->assignments->sortByDesc('assigned_at') as $assignment)<article class="rounded-lg border border-line p-4 text-sm"><p class="font-bold">{{ $assignment->user->name }}</p><p class="mt-1 text-muted">{{ $assignment->assigned_at->format('d M Y') }} &mdash; {{ $assignment->returned_at?->format('d M Y') ?? 'Aktif' }}</p><p class="mt-2 text-xs text-muted">Kondisi: {{ str($assignment->condition_when_assigned)->replace('_', ' ')->title() }} &rarr; {{ str($assignment->condition_when_returned ?? '-')->replace('_', ' ')->title() }}</p></article>@empty<x-empty-state title="Belum ada penugasan" description="Riwayat pengguna aset akan tampil di sini." icon="users" />@endforelse</div></x-panel>
        <x-panel title="Riwayat perbaikan"><div class="space-y-3">@forelse($asset->repairs->sortByDesc('repair_date') as $repair)<a href="{{ route('repairs.show', $repair) }}" class="block rounded-lg border border-line p-4 text-sm transition hover:border-accent"><div class="flex justify-between gap-3"><span class="font-bold">{{ $repair->repair_date->format('d M Y') }}</span><span>Rp {{ number_format($repair->repair_cost, 0, ',', '.') }}</span></div><p class="mt-1 text-muted">{{ str($repair->result)->replace('_', ' ')->title() }} &middot; {{ $repair->technician->name }}</p></a>@empty<x-empty-state title="Belum ada perbaikan" description="Catatan perbaikan aset akan tampil di sini." icon="wrench" />@endforelse</div></x-panel>
    </div>
    <x-panel title="Tiket terkait" class="mt-6"><div class="table-wrap"><table class="table"><thead><tr><th>Nomor</th><th>Judul</th><th>Status</th></tr></thead><tbody>@forelse($asset->tickets as $ticket)<tr><td><a class="font-bold text-accent hover:text-accent-dark" href="{{ route('tickets.show', $ticket) }}">{{ $ticket->ticket_number }}</a></td><td class="!whitespace-normal">{{ $ticket->title }}</td><td><x-badge :value="$ticket->status" /></td></tr>@empty<tr><td colspan="3" class="!p-0"><x-empty-state title="Belum ada tiket terkait" description="Tiket yang memilih aset ini akan tampil di sini." icon="ticket" /></td></tr>@endforelse</tbody></table></div></x-panel>
</x-app-layout>
